#!C:\DSIR12\MachineLearning\TPS\TP 9 MLops-20250428\TP_MLOps\mlops_env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
